/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shell.h"

int *
add_1_svc(CMDS *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("parameters: %s\n", argp->cmd);
	return &result;
}
