/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shell.h"
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

#include <sys/types.h>
#include <sys/wait.h>

void execfs(char* cmd) {
  //arguments for ls, will run: ls  -l /bin
  char * ls_args[4] = { "./fs_rpc", cmd,  NULL} ;
  pid_t c_pid, pid;
  int status;

  c_pid = fork();

  if (c_pid == 0){
    /* CHILD */

    printf("Child: executing %s\n", cmd);

    //execute ls
    execvp( ls_args[0], ls_args);
    //only get here if exec failed
    perror("execve failed");
  }else if (c_pid > 0){
    /* PARENT */

    if( (pid = wait(&status)) < 0){
      perror("wait");
      _exit(1);
    }

    printf("Parent: finished\n");

  }else{
    perror("fork failed");
    _exit(1);
  }
  
}

char* readResult() {
  char * buffer = 0;
  long length;
  FILE * f = fopen ("tmp", "rb");

  if (f)
  {
    fseek (f, 0, SEEK_END);
    length = ftell (f);
    fseek (f, 0, SEEK_SET);
    buffer = malloc (length);
    if (buffer)
  	{
  	  fread (buffer, 1, length, f);
  	}
    fclose (f);
  }
  return buffer;
}


char **
printmessage_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	int SIZE = 1024;
	
	/* char string[SIZE]; */
	/* freopen("/dev/null", "a", stdout); */
	/* freopen("/dev/null", "a", stderr); */
	/* setbuf(stdout, string); */

	
	/*
	 * insert server code here
	 */
	execfs(*argp);
	char* buffer = readResult();
	printf(buffer);
	//printf("servre: %s\n", *argp);


	result = buffer;
	return &result;
}
