/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shell.h"
#include <stdio.h>

void
messageprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * printmessage_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGEPROG, MESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char cmd[1024];
	while(1) {
	  //char* cmd;
	  size_t len = 0;
	  
	  printf("client$ ");
	  gets(cmd);
	  //getline(&cmd, &len, stdin);
	  printmessage_1_arg = cmd;
//printf("sent: %s$", cmd);
	  result_1 = printmessage_1(&printmessage_1_arg, clnt);
	  if (result_1 == (char **) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	  else {
	    printf(*result_1);
	  }
        }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	messageprog_1 (host);
exit (0);
}
